---
- name: Set GNOME settings for buttons and dark mode
  hosts: localhost
  tasks:
    - name: Set button layout to 'close,minimize,maximize'
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'"

    - name: Set GTK theme to dark
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'"
